### ISSUE TITLE
I got this bug when trying to enable hoi4 dlc

### ISSUE THREAD

**Issue by KentuckyFriedAss** [pointfeev/CreamInstaller#202]
###### Describe the bug and/or provide an image of the exception dialog box:
[16387] System.NullReferenceException: Object reference not set to an instance of an object.
    at CreamInstaller.Forms.SelectForm.<>c__DisplayClass36_0.<OnLoadDlc>b__0(ValueTuple`3 c)
        in CreamInstaller\Forms\SelectForm.cs
            on line 981
    at System.Linq.Enumerable.AnyTSource
    at CreamInstaller.Forms.SelectForm.OnLoadDlc(Object sender, EventArgs e)
        in CreamInstaller\Forms\SelectForm.cs
            on line 981
    at CreamInstaller.Forms.SelectForm.OnLoad(Boolean forceScan, Boolean forceProvideChoices)
        in CreamInstaller\Forms\SelectForm.cs
            on line 621
    at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_0(Object state)
    at InvokeStub_SendOrPostCallback.Invoke(Object, Span`1)
    at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)

**Comment by pointfeev** [comment]
This should be fixed in the next update.
